import { useQuery } from "@tanstack/react-query";
import { Download } from "lucide-react";

import { Button } from "@/components/ui/button";
import { fetchJobOrders } from "@/features/jobs/api";
import { JOB_PRIORITY_LABEL, JOB_STATUS_LABEL, shortJobId } from "@/lib/laboratory";
import { isQcManager } from "@/lib/staff";
import { useAuthStore } from "@/stores/auth-store";

import { LIMS_EXTENSION_PAGE_SIZE } from "@/lib/staff/lims-extensions/constants";
import { LimsPageIntro } from "../lims-page-intro";
import { StaffRoleBanner } from "../staff-role-banner";

/**
 * Backend: no COA/PDF — completed jobs are available via jobs API with `current_status=completed`.
 */
export default function StaffReportsPage() {
  const user = useAuthStore((s) => s.user);
  const qcManager = isQcManager(user);

  const { data, isLoading, isError } = useQuery({
    queryKey: ["lims-reports-completed-jobs"],
    queryFn: () =>
      fetchJobOrders({
        page: 1,
        current_status: "completed",
        is_cancelled: false,
      }),
    staleTime: 60_000,
  });

  function downloadCsv() {
    if (!data?.results.length) return;
    const headers = qcManager
      ? ["job_short_id", "priority", "sample_count", "updated_at"]
      : ["job_short_id", "client", "priority", "sample_count", "updated_at"];
    const rows = data.results.map((j) => {
      const cols = qcManager
        ? [
            shortJobId(j.id),
            j.priority,
            String(j.sample_count),
            j.updated_at,
          ]
        : [
            shortJobId(j.id),
            j.client,
            j.priority,
            String(j.sample_count),
            j.updated_at,
          ];
      return cols.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(",");
    });
    const content = [headers.join(","), ...rows].join("\n");
    const blob = new Blob([content], {
      type: "text/csv;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `lsims-completed-jobs-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-8">
      <LimsPageIntro title="Reports &amp; completion register">
        <p>
          Formal certificates of analysis (COA) are not generated by this API. You can export a
          CSV snapshot of <strong>{JOB_STATUS_LABEL.completed}</strong> jobs from the data the
          backend already exposes.
        </p>
        {qcManager ? (
          <p className="mt-2 text-sm text-muted-foreground">
            Completed jobs shown here are limited to those your department touches — the jobs API
            enforces department scope for department managers.
          </p>
        ) : null}
      </LimsPageIntro>

      <StaffRoleBanner />

      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-sm">
        <p className="text-sm text-muted-foreground">
          {data
            ? qcManager
              ? `${data.count} completed job(s) in your department`
              : `${data.count} completed job(s) in the system`
            : "Loading totals…"}
        </p>
        <Button
          type="button"
          variant="secondary"
          size="sm"
          className="gap-1"
          disabled={!data?.results.length}
          onClick={downloadCsv}
        >
          <Download className="size-4" />
          Export page to CSV
        </Button>
      </div>

      <div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
        {isLoading ? (
          <div className="p-8 text-center text-muted-foreground">Loading…</div>
        ) : isError ? (
          <p className="p-4 text-destructive">Could not load jobs.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-left text-sm">
              <thead>
                <tr className="border-b bg-muted/40">
                  <th className="px-4 py-3 font-medium">Job</th>
                  {!qcManager ? (
                    <th className="px-4 py-3 font-medium">Client</th>
                  ) : null}
                  <th className="px-4 py-3 font-medium">Priority</th>
                  <th className="px-4 py-3 font-medium">Samples</th>
                  <th className="px-4 py-3 font-medium">Completed / updated</th>
                </tr>
              </thead>
              <tbody>
                {data?.results.slice(0, LIMS_EXTENSION_PAGE_SIZE).map((j) => (
                  <tr key={j.id} className="border-b border-border">
                    <td className="px-4 py-3 font-mono text-xs">{shortJobId(j.id)}</td>
                    {!qcManager ? (
                      <td className="px-4 py-3 text-muted-foreground">{j.client}</td>
                    ) : null}
                    <td className="px-4 py-3 capitalize">
                      {JOB_PRIORITY_LABEL[j.priority]}
                    </td>
                    <td className="px-4 py-3 tabular-nums">{j.sample_count}</td>
                    <td className="px-4 py-3 text-xs text-muted-foreground">
                      {new Date(j.updated_at).toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
