# Generated by Django 6.0.2 on 2026-03-12 14:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Auto-generated anonymous identifier (e.g., 'BC-A3K9F2').", max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blind_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text="Full name of the analysis test (e.g., 'Gold Fire Assay').", max_length=200, unique=True)),
                ('test_code', models.CharField(help_text="Short identifier code (e.g., 'GFA-01').", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the test procedure and purpose.')),
                ('unit', models.CharField(help_text="Measurement unit for results (e.g., 'ppm', '%%', 'mg/kg').", max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per test in ETB.', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tests are hidden from selection but preserved for history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Catalog Entry',
                'verbose_name_plural': 'Test Catalog',
                'db_table': 'test_catalog',
                'ordering': ['test_code'],
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received'), ('in_prep', 'In Preparation'), ('in_analysis', 'In Analysis'), ('qc', 'Quality Control'), ('finance_hold', 'Finance Hold'), ('completed', 'Completed')], default='received', help_text='Current workflow stage of the job.', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='', help_text="Explanation of current delay or hold (e.g., 'Waiting for Prep').")),
                ('is_cancelled', models.BooleanField(default=False, help_text='Whether this job has been cancelled.')),
                ('cancellation_reason', models.TextField(blank=True, default='', help_text='Reason for cancellation (required if is_cancelled=True).')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', help_text='Processing priority level.', max_length=10)),
                ('description', models.TextField(blank=True, default='', help_text='General notes or description for this job order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by_role', models.ForeignKey(blank=True, help_text='Role responsible for the next action on this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocking_jobs', to='accounts.role')),
                ('client', models.ForeignKey(help_text='External client who owns this job.', on_delete=django.db.models.deletion.PROTECT, related_name='job_orders_as_client', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='Receptionist who registered this job.', on_delete=django.db.models.deletion.PROTECT, related_name='job_orders_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Order',
                'verbose_name_plural': 'Job Orders',
                'db_table': 'job_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_code', models.CharField(help_text="Human-readable sequential code (e.g., 'SMP-2026-0001').", max_length=20, unique=True)),
                ('sample_name', models.CharField(help_text="Descriptive name of the sample (e.g., 'Quartz Ore — Site B').", max_length=200)),
                ('sample_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight of the sample in grams.', max_digits=10, null=True)),
                ('packaging_type', models.CharField(blank=True, default='', help_text="Type of packaging (e.g., 'Sealed Bag', 'Plastic Container').", max_length=100)),
                ('collection_date', models.DateField(blank=True, help_text='Date the sample was collected in the field.', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When the analyst was assigned.', null=True)),
                ('reassigned_reason', models.TextField(blank=True, default='', help_text='Reason for reassigning to a different analyst.')),
                ('sample_status', models.CharField(choices=[('registered', 'Registered'), ('in_queue', 'In Queue'), ('in_prep', 'In Preparation'), ('pending_analysis', 'Pending Analysis'), ('in_analysis', 'In Analysis'), ('completed', 'Completed')], default='registered', help_text='Current processing status of the sample.', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about the sample.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, help_text='Lab Analyst assigned to work on this sample.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_samples', to=settings.AUTH_USER_MODEL)),
                ('blind_alias', models.OneToOneField(help_text='Auto-assigned anonymous code for blind analysis.', on_delete=django.db.models.deletion.PROTECT, related_name='sample', to='laboratory.blindcode')),
                ('job', models.ForeignKey(help_text='Parent job order this sample belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='laboratory.joborder')),
                ('received_by', models.ForeignKey(help_text='Receptionist who received this sample.', on_delete=django.db.models.deletion.PROTECT, related_name='samples_received', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='Client who submitted this sample.', on_delete=django.db.models.deletion.PROTECT, related_name='samples_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(help_text='The sample to be tested.', on_delete=django.db.models.deletion.CASCADE, related_name='sample_tests', to='laboratory.sample')),
                ('test', models.ForeignKey(help_text='The test to perform on this sample.', on_delete=django.db.models.deletion.PROTECT, related_name='sample_tests', to='laboratory.testcatalog')),
            ],
            options={
                'verbose_name': 'Sample Test Assignment',
                'verbose_name_plural': 'Sample Test Assignments',
                'db_table': 'sample_tests',
                'ordering': ['-created_at'],
                'unique_together': {('sample', 'test')},
            },
        ),
    ]
