# Generated by Django 6.0.2 on 2026-04-14 10:46

import django.db.models.deletion
import laboratory.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_backfill_sample_code_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='current_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('payment_pending', 'Payment Pending'), ('received', 'Received'), ('in_prep', 'In Preparation'), ('in_analysis', 'In Analysis'), ('qc', 'Quality Control'), ('finance_hold', 'Finance Hold'), ('completed', 'Completed')], default='payment_pending', help_text='Current workflow stage of the job.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='blind_alias',
            field=models.OneToOneField(blank=True, help_text='Auto-assigned anonymous code for blind analysis.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample', to='laboratory.blindcode'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_code',
            field=models.CharField(blank=True, help_text="Human-readable sequential code (e.g., 'SMP-2026-0001').", max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('invoice_no', models.CharField(default=laboratory.models.generate_invoice_no, help_text='Unique invoice number for this job.', max_length=32, primary_key=True, serialize=False)),
                ('amount_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(help_text='Job order covered by this financial record.', on_delete=django.db.models.deletion.CASCADE, related_name='financial_record', to='laboratory.joborder')),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'db_table': 'financial_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
