# Generated by Django 6.0.2 on 2026-04-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_user_department'),
        ('laboratory', '0004_alter_joborder_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcatalog',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='accounts.department'),
        ),
    ]
