# Generated by Django 6.0.2 on 2026-04-14 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def normalize_user_profile_enums(apps, schema_editor):
    User = apps.get_model('accounts', 'User')

    organization_type_map = {
        '': 'other',
        'government': 'government',
        'government organization': 'government',
        'governmental organization': 'government',
        'private': 'private',
        'mining company': 'private',
        'university': 'university',
        'university / research': 'university',
        'university or research institution': 'university',
        'university_or_research_institution': 'university',
        'individual': 'individual',
        'ngo': 'ngo',
        'non-governmental organization': 'ngo',
        'non_governmental_organization': 'ngo',
        'other': 'other',
    }

    for user in User.objects.all().iterator():
        normalized_org_type = organization_type_map.get(
            (user.organization_type or '').strip().lower(),
            'other',
        )
        nationality = (user.nationality or '').strip().lower()
        if nationality in {'ethiopian', 'ethiopia'}:
            country = 'ethiopia'
        elif nationality:
            country = 'other'
        else:
            country = user.country or 'ethiopia'

        if user.organization_type != normalized_org_type or user.country != country:
            user.organization_type = normalized_org_type
            user.country = country
            user.save(update_fields=['organization_type', 'country'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('ethiopia', 'Ethiopia'), ('other', 'Other')], default='ethiopia', help_text='Country associated with this user or client profile.', max_length=20),
        ),
        migrations.RunPython(normalize_user_profile_enums, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('university', 'University'), ('individual', 'Individual'), ('ngo', 'NGO'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
