# Generated by Django 6.0.2 on 2026-04-08 13:48

from django.db import migrations, models


def forwards_map_legacy_sample_statuses(apps, schema_editor):
    Sample = apps.get_model("laboratory", "Sample")
    legacy_map = {
        "registered": "received",
        "in_queue": "submitted",
        "pending_analysis": "in_prep",
    }
    for old, new in legacy_map.items():
        Sample.objects.filter(sample_status=old).update(sample_status=new)

    valid = {
        "draft",
        "submitted",
        "received",
        "in_prep",
        "in_analysis",
        "qc",
        "finance_hold",
        "completed",
    }
    for sample in Sample.objects.select_related("job").iterator():
        if sample.sample_status in valid:
            continue
        fallback = (
            sample.job.current_status
            if sample.job_id and sample.job.current_status in valid
            else "received"
        )
        Sample.objects.filter(pk=sample.pk).update(sample_status=fallback)


def noop_reverse(apps, schema_editor):
    pass


def forwards_resync_samples_with_jobs(apps, schema_editor):
    Sample = apps.get_model("laboratory", "Sample")
    for sample in (
        Sample.objects.filter(status_sync_with_job=True)
        .select_related("job")
        .iterator()
    ):
        if not sample.job_id:
            continue
        target = sample.job.current_status
        if sample.sample_status != target:
            Sample.objects.filter(pk=sample.pk).update(sample_status=target)


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_backfill_sample_code_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='status_sync_with_job',
            field=models.BooleanField(default=True, help_text="When True, sample_status is kept in sync with the parent job's current_status (automatic workflow). When False, staff can set sample_status independently."),
        ),
        migrations.RunPython(forwards_map_legacy_sample_statuses, noop_reverse),
        migrations.AlterField(
            model_name='sample',
            name='sample_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received'), ('in_prep', 'In Preparation'), ('in_analysis', 'In Analysis'), ('qc', 'Quality Control'), ('finance_hold', 'Finance Hold'), ('completed', 'Completed')], default='received', help_text='Current processing status of the sample.', max_length=20),
        ),
        migrations.RunPython(forwards_resync_samples_with_jobs, noop_reverse),
    ]
