# Generated by Django 6.0.2 on 2026-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_sample_workflow_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='current_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_finance', 'Pending finance'), ('received', 'Received'), ('in_prep', 'In Preparation'), ('in_analysis', 'In Analysis'), ('qc', 'Quality Control'), ('finance_hold', 'Finance Hold'), ('completed', 'Completed')], default='received', help_text='Current workflow stage of the job.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_finance', 'Pending finance'), ('received', 'Received'), ('in_prep', 'In Preparation'), ('in_analysis', 'In Analysis'), ('qc', 'Quality Control'), ('finance_hold', 'Finance Hold'), ('completed', 'Completed')], default='received', help_text='Current processing status of the sample.', max_length=20),
        ),
    ]
