# Generated by Django 6.0.2 on 2026-07-01 08:37

import django.db.models.deletion
import laboratory.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_lab_director_role'),
        ('laboratory', '0006_sample_received_by_optional_client_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcatalog',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='blind_alias',
            field=models.OneToOneField(blank=True, help_text='Auto-assigned anonymous code for blind analysis.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample', to='laboratory.blindcode'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_code',
            field=models.CharField(blank=True, help_text="Human-readable sequential code (e.g., 'SMP-2026-0001').", max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for QC'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('value', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('method', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(blank=True, help_text='Analyst responsible for this result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to=settings.AUTH_USER_MODEL)),
                ('sample_test', models.OneToOneField(help_text='Sample test this result satisfies.', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='laboratory.sampletest')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=200)),
                ('calibration_reference', models.CharField(blank=True, default='', max_length=200)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('calibration_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='laboratory.analysisresult')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calibration Record',
                'verbose_name_plural': 'Calibration Records',
                'db_table': 'calibration_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('payment', 'Payment'), ('sample', 'Sample'), ('result', 'Result'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='laboratory.joborder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_resolved', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='laboratory.sample')),
            ],
            options={
                'verbose_name': 'Complaint Record',
                'verbose_name_plural': 'Complaint Records',
                'db_table': 'complaint_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('free_test', 'Free Test')], max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_approvals', to='laboratory.joborder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_approvals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Approval',
                'verbose_name_plural': 'Discount Approvals',
                'db_table': 'discount_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('invoice_no', models.CharField(default=laboratory.models.generate_invoice_no, help_text='Unique invoice number for this job.', max_length=32, primary_key=True, serialize=False)),
                ('amount_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_required', models.BooleanField(default=True, help_text='When false, an approved waiver bypasses the payment gate.')),
                ('waiver_reason', models.TextField(blank=True, default='', help_text='Reason payment was waived for this job.')),
                ('waiver_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(help_text='Job order covered by this financial record.', on_delete=django.db.models.deletion.CASCADE, related_name='financial_record', to='laboratory.joborder')),
                ('waiver_approved_by', models.ForeignKey(blank=True, help_text='User who approved the payment waiver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_waivers_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'db_table': 'financial_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(default=laboratory.models.generate_preparation_reference, help_text='Internal preparation reference code.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('preparation_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_records_created', to=settings.AUTH_USER_MODEL)),
                ('sample', models.OneToOneField(help_text='Paid/coded sample being prepared for analysis.', on_delete=django.db.models.deletion.CASCADE, related_name='preparation_record', to='laboratory.sample')),
                ('technician', models.ForeignKey(blank=True, help_text='Lab Technician assigned to preparation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preparation Record',
                'verbose_name_plural': 'Preparation Records',
                'db_table': 'preparation_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_decisions', to='laboratory.analysisresult')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QC Decision',
                'verbose_name_plural': 'QC Decisions',
                'db_table': 'qc_decisions',
                'ordering': ['-decided_at'],
            },
        ),
    ]
